### ISSUE TITLE
RazorViewEngineOptions for FileProviders in ASP.NET Core 3.0 

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#14593]
Moved from https://github.com/aspnet/AspNetCore.Docs/issues/14586 (EDIT by @guardrex to place code block into remark).

@zhou881117 remarks ...

> ```csharp
> services.Configure(options =>
> {
>     options.FileProviders.Add(
>         new EmbeddedFileProvider(typeof(MySharedController).GetTypeInfo().Assembly));
> });
> ```
> .net core 3.0 RazorViewEngineOptions changed. without FileProviders to locate view
> 
> @Rick-Anderson
> tks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d8787c1-1a02-ae68-aa59-7c0e2e823dde
* Version Independent ID: 3e799e5d-a89c-cd03-999f-92ae431f4657
* Content: [File Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/file-providers?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/file-providers.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/file-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This topic+sample was updated for 3.0 on https://github.com/aspnet/AspNetCore.Docs/pull/14027.

I'll take a look, but I'm 🏃 at the moment and won't be able to get to this for perhaps a week or two.

**Comment by Rick-Anderson** [comment]
5.5 K PV/month.

**Comment by zhou881117** [comment]
Ah...   3.0 could solve it?

**Comment by alexkyse1** [comment]
Perhaps this solution will work.

.NET Core 2 by installing **Microsoft.AspNetCore.Mvc.Razor** nuget package

```csharp
services.Configure<RazorViewEngineOptions>(options => {
	options.FileProviders.Clear();
	options.FileProviders.Add(new PhysicalFileProvider(appDirectory));
});
```

.NET Core 3 by installing **Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation** nuget package

```csharp
services.Configure<MvcRazorRuntimeCompilationOptions>(options => {
	options.FileProviders.Clear();
	options.FileProviders.Add(new PhysicalFileProvider(appDirectory));
});
```

**Comment by Turnerj** [comment]
On the [File Providers](https://docs.microsoft.com/en-au/aspnet/core/fundamentals/file-providers?view=aspnetcore-3.0) page in the docs, it does link to example code which uses DI to inject the provider for the `IFileProvider` interface.

https://github.com/aspnet/AspNetCore.Docs/blob/d0ab5e5f44ea0ca42bfd608e12f7e04583aa5936/aspnetcore/fundamentals/file-providers/samples/3.x/FileProviderSample/Startup.cs#L23-L31

That however doesn't seem to work for MVC Razor views when using `ManifestEmbeddedFileProvider`.

In my case, I'm doing integration testing in a second project which needs to launch a custom site startup in this second project but pull in the controllers and views from the first/reference project. The controllers are brought in via `AddApplicationPart` but even with embedded views and the `ManifestEmbeddedFileProvider`, the views aren't accessible when that provider is set as the implementation of `IFileProvider` - it says the views can't be found.

```
The view 'Login' was not found. The following locations were searched:
/Areas/Accounts/Views/Home/Login.cshtml
/Areas/Accounts/Views/Shared/Login.cshtml
/Views/Shared/Login.cshtml
```
I did check the provider directly in a debug session - the views are definitely there and at the paths being looked at - does MVC actually use DI for the Razor file provider or just reference the "Views" library directly?

**Comment by zhou881117** [comment]
services.Configure<Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.MvcRazorRuntimeCompilationOptions>(options =>
            {
                options.FileProviders.Clear(); 
                options.FileProviders.Add(new PhysicalFileProvider(AppContext.BaseDirectory));
                options.FileProviders.Add(new EmbeddedFileProvider(typeof(IntelligentFactory.Web.PluginAdmin.AdminProfile).Assembly));
                //new PhysicalFileProvider(appDirectory));
            });

MvcRazorRuntimeCompilationOptions also not work.

> Perhaps this solution will work.
> 
> .NET Core 2 by installing **Microsoft.AspNetCore.Mvc.Razor** nuget package
> 
> ```cs
> services.Configure<RazorViewEngineOptions>(options => {
> 	options.FileProviders.Clear();
> 	options.FileProviders.Add(new PhysicalFileProvider(appDirectory));
> });
> ```
> 
> .NET Core 3 by installing **Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation** nuget package
> 
> ```cs
> services.Configure<MvcRazorRuntimeCompilationOptions>(options => {
> 	options.FileProviders.Clear();
> 	options.FileProviders.Add(new PhysicalFileProvider(appDirectory));
> });
> ```



> Perhaps this solution will work.
> 
> .NET Core 2 by installing **Microsoft.AspNetCore.Mvc.Razor** nuget package
> 
> ```cs
> services.Configure<RazorViewEngineOptions>(options => {
> 	options.FileProviders.Clear();
> 	options.FileProviders.Add(new PhysicalFileProvider(appDirectory));
> });
> ```
> 
> .NET Core 3 by installing **Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation** nuget package
> 
> ```cs
> services.Configure<MvcRazorRuntimeCompilationOptions>(options => {
> 	options.FileProviders.Clear();
> 	options.FileProviders.Add(new PhysicalFileProvider(appDirectory));
> });
> ```

services.Configure<Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.MvcRazorRuntimeCompilationOptions>(options =>
            {
                options.FileProviders.Clear(); 
                options.FileProviders.Add(new PhysicalFileProvider(AppContext.BaseDirectory));
                options.FileProviders.Add(new EmbeddedFileProvider(typeof(IntelligentFactory.Web.PluginAdmin.AdminProfile).Assembly));
                //new PhysicalFileProvider(appDirectory));
            });

MvcRazorRuntimeCompilationOptions also not work.

may this is not runtime razor.

**Comment by zhou881117** [comment]
> Perhaps this solution will work.
> 
> .NET Core 2 by installing **Microsoft.AspNetCore.Mvc.Razor** nuget package
> 
> ```cs
> services.Configure<RazorViewEngineOptions>(options => {
> 	options.FileProviders.Clear();
> 	options.FileProviders.Add(new PhysicalFileProvider(appDirectory));
> });
> ```
> 
> .NET Core 3 by installing **Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation** nuget package
> 
> ```cs
> services.Configure<MvcRazorRuntimeCompilationOptions>(options => {
> 	options.FileProviders.Clear();
> 	options.FileProviders.Add(new PhysicalFileProvider(appDirectory));
> });
> ```

services.Configure<Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.MvcRazorRuntimeCompilationOptions>(options =>
            {
                options.FileProviders.Clear(); 
                options.FileProviders.Add(new PhysicalFileProvider(AppContext.BaseDirectory));
                options.FileProviders.Add(new EmbeddedFileProvider(typeof(IntelligentFactory.Web.PluginAdmin.AdminProfile).Assembly));
                //new PhysicalFileProvider(appDirectory));
            });

MvcRazorRuntimeCompilationOptions is also not work.
may this is not runtime razor.

**Comment by nexon33** [comment]
for me, MvcRazorRuntimeCompilationOptions also doesn't work, although I can successfully add the code and it throws no error, the views are not found during runtime.

**Comment by nexon33** [comment]
After a lot of searching managed to solve it, the above code stated is correct. But you will also need to change `services.AddRazorPages();` to `services.AddRazorPages().AddRazorRuntimeCompilation();` because else you end up configuring something that isn't used anywhere in the project.

**Comment by guardrex** [comment]
This is misplaced here ... my bad. This is for the *View Complication* topic, where some of the updates for 3.0 were made and one update doesn't seem correct based on the [announcement](https://github.com/aspnet/Announcements/issues/343). I'll move this issue over and ping all of you on the new issue.

**Comment by zhou881117** [comment]
how to run app-parts  correct  .net core 3.0?
this is my question.

the demo dosen't not work well for .net core 3.0
https://github.com/aspnet/AspNetCore.Docs/tree/5bbb2f5c459cf9bcc1159278a52555cc0f4bb3f6/aspnetcore/mvc/advanced/app-parts
@guardrex

**Comment by jjxtra** [comment]
Trying this but get a ton of errors. I've already put in my csproj the suggested value...

```cs
One or more compilation references may be missing. If you're seeing this in a published application, set 'CopyRefAssembliesToPublishDirectory' to true in your project file to ensure files in the refs directory are published.

... thousands of missing type errors ...
```

**Comment by jjxtra** [comment]
Going back to .net core 2.2, this is a mess...

**Comment by Rick-Anderson** [comment]
@jjxtra can you open an issue at https://github.com/aspnet/AspNetCore with the simplest possible repo? This is a closed issue in the doc's repo, not the asp.net core code repo.

**Comment by littlesmilelove** [comment]
> After a lot of searching managed to solve it, the above code stated is correct. But you will also need to change `services.AddRazorPages();` to `services.AddRazorPages().AddRazorRuntimeCompilation();` because else you end up configuring something that isn't used anywhere in the project.

After doing that, I get a new exception : `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.CompilationFailedException: One or more compilation failures occurred`
`rq42brze.pko(4,20): error CS0400: The type or namespace name 'Microsoft' could not be found in the global namespace (are you missing an assembly reference?)`

**Comment by littlesmilelove** [comment]
> how to run app-parts correct .net core 3.0?
> this is my question.
> 
> the demo dosen't not work well for .net core 3.0
> https://github.com/aspnet/AspNetCore.Docs/tree/5bbb2f5c459cf9bcc1159278a52555cc0f4bb3f6/aspnetcore/mvc/advanced/app-parts
> @guardrex
> 
> Maybe they are the seem question #14800 ?

The same issue, app-parts with razor views can't work in .net core 3.0.

**Comment by jjxtra** [comment]
There is some voodoo involved, I have solved most of it with this (except unit testing razor) here: https://github.com/aspnet/AspNetCore/issues/14952

**Comment by Rick-Anderson** [comment]
@Tratcher  what's the trick to get the following code to compile in 3.0?

```
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<RazorViewEngineOptions>(options =>
    {
        options.FileProviders.Add(   // <-------
         new EmbeddedFileProvider(typeof(MySharedController).GetTypeInfo().Assembly));
    });
}
```

'RazorViewEngineOptions' does not contain a definition for 'FileProviders' and no accessible extension method 'FileProviders' accepting a first argument of type 'RazorViewEngineOptions' could be found 

cc @serpent5 @guardrex

**Comment by Rick-Anderson** [comment]
Never mind
`MvcRazorRuntimeCompilationOptions` works

**Comment by Rick-Anderson** [comment]
@serpent5  now I get 
The type or namespace name 'MvcRazorRuntimeCompilationOptions' could not be found (are you missing a using directive or an assembly reference?)

**Comment by Rick-Anderson** [comment]
https://github.com/aspnet/Announcements/issues/343

**Comment by serpent5** [comment]
Have you got it working now?

**Comment by Rick-Anderson** [comment]
No

**Comment by serpent5** [comment]
You need the `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` NuGet package and these usings:

```csharp
using Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation;
using Microsoft.Extensions.FileProviders;
```

Here's the code itself for completeness:

```csharp
services.Configure<MvcRazorRuntimeCompilationOptions>(options =>
{
    options.FileProviders.Add(
        new EmbeddedFileProvider(typeof(MySharedController).GetTypeInfo().Assembly));
});
```

**Comment by zhou881117** [comment]
yes,it's ok.

>  public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.MvcRazorRuntimeCompilationOptions>(options =>
            {
                options.FileProviders.Add(
                    new EmbeddedFileProvider(typeof(MySharedController).GetTypeInfo().Assembly));
            });
            // Requires using System.Reflection;
            var assembly = typeof(MySharedController).GetTypeInfo().Assembly;
            services.AddMvc().AddRazorRuntimeCompilation()
               .AddApplicationPart(assembly)
               .SetCompatibilityVersion(CompatibilityVersion.Version_3_0);
        }

Both of 

> MvcRazorRuntimeCompilationOptions 、AddRazorRuntimeCompilation

[https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/mvc/advanced/app-parts](url)
